// <auto-generated />
using System;
using EntrepreneurBuddy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntrepreneurBuddy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191026033235_added-entre-relation")]
    partial class addedentrerelation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntrepreneurBuddy.Models.Entrepenuer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("MentoringRequestId");

                    b.HasKey("Id");

                    b.HasIndex("MentoringRequestId");

                    b.ToTable("Entrepenuers");
                });

            modelBuilder.Entity("EntrepreneurBuddy.Models.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bio");

                    b.Property<string>("FirstName");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("LastName");

                    b.Property<string>("Position");

                    b.Property<int>("Rating");

                    b.Property<string>("Skills");

                    b.Property<string>("Zip");

                    b.HasKey("Id");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("EntrepreneurBuddy.Models.MentoringRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("MentorId");

                    b.Property<string>("Topic");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("MentoringRequests");
                });

            modelBuilder.Entity("EntrepreneurBuddy.Models.Entrepenuer", b =>
                {
                    b.HasOne("EntrepreneurBuddy.Models.MentoringRequest")
                        .WithMany()
                        .HasForeignKey("MentoringRequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntrepreneurBuddy.Models.MentoringRequest", b =>
                {
                    b.HasOne("EntrepreneurBuddy.Models.Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
